# Generated by Django 3.2.9 on 2022-02-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.TextField(max_length=10)),
                ('name2', models.TextField(max_length=10)),
            ],
        ),
    ]
